services:
  db:
    platform: linux/amd64
    image: postgis/postgis:17-3.5
    container_name: geoportal_postgis_db
    environment:
      POSTGRES_USER: geoportal_user
      POSTGRES_PASSWORD: geoportal_pass
      POSTGRES_DB: geoportal_db
    volumes:
      - geoportal_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - geoportal_net

  mapserver:
    image: camptocamp/mapserver:605-arm64
    container_name: geoportal_mapserver
    environment:
      - MS_MAPFILE=/etc/mapserver/geoportal.map
    ports:
      - "8080:80"
    volumes:
      - ./mapserver/conf:/etc/mapserver:ro
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - geoportal_net

volumes:
  geoportal_pgdata:
    driver: local

networks:
  geoportal_net:
    driver: bridge
